# Generated by Django 3.2 on 2021-07-27 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('marca', models.CharField(max_length=100, null=True)),
                ('categoria', models.TextField(null=True)),
                ('tienda', models.CharField(max_length=200, null=True)),
                ('pais', models.CharField(max_length=100, null=True)),
                ('ingredientes', models.TextField(null=True)),
                ('alergenos', models.TextField(null=True)),
                ('aditivos', models.TextField(null=True)),
                ('puntuacion_nova', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('image_url', models.CharField(max_length=200, null=True)),
                ('image_small_url', models.CharField(max_length=200, null=True)),
                ('calorias', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('energia', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('grasa', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('grasas_saturadas', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('colesterol', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('carbohidratos', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('azucares', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('fibra', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('proteinas', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('sal', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('sodio', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('calcio', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('hierro', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('puntuacion', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=200, unique=True, verbose_name='Usuario')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('nombre', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(max_length=10, null=True)),
                ('altura', models.IntegerField(blank=True, null=True)),
                ('peso', models.IntegerField(blank=True, null=True)),
                ('imagen', models.ImageField(max_length=200, null=True, upload_to='perfil/', verbose_name='Imagen de perfil')),
                ('administrador', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, null=True)),
                ('descripcion', models.TextField(max_length=200, null=True)),
                ('productos', models.ManyToManyField(to='aplicacion.Producto')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.usuario')),
            ],
        ),
    ]
