# Generated by Django 3.2.6 on 2021-08-11 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='image_small_url',
        ),
    ]
