# Generated by Django 3.2.6 on 2021-08-18 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_remove_producto_image_small_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='image_url',
        ),
    ]
