# Generated by Django 3.1.7 on 2021-03-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=200)),
                ('calorias', models.CharField(max_length=200)),
                ('hidratos', models.CharField(max_length=200)),
                ('grasa', models.CharField(max_length=200)),
                ('proteinas', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='Autor',
            new_name='Usuario',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='libro',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Libro',
        ),
        migrations.DeleteModel(
            name='Prestamo',
        ),
    ]
