# Generated by Django 3.1.7 on 2021-03-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0002_auto_20210318_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='Blank', upload_to='productos'),
        ),
    ]
